Update docker images...

diff --git a/Dockerfile.alpine b/Dockerfile.alpine
--- a/Dockerfile.alpine
+++ b/Dockerfile.alpine
@@ -44,49 +44,46 @@
 #                                                                                                      #
 ########################################################################################################
 
-FROM openjdk:8u191-jdk-alpine3.8
+#FROM openjdk:8u191-jdk-alpine3.8
+FROM openjdk:8u212-jdk-alpine3.9
 LABEL MAINTAINER='Maksim Kostromin <daggerok@gmail.com>'
-ENV PRODUCT='jboss-eap-7.2'                                                                            \
+ENV PRODUCT='jboss-eap-7.2'                                                         \
     JBOSS_USER='jboss'
-ENV ADMIN_USER='admin'                                                                                 \
-    ADMIN_PASSWORD='Admin.123'                                                                         \
-    JBOSS_USER_HOME="/home/${JBOSS_USER}"                                                              \
-    DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download"                       \
+ENV ADMIN_USER='admin'                                                              \
+    ADMIN_PASSWORD='Admin.123'                                                      \
+    JBOSS_USER_HOME="/home/${JBOSS_USER}"                                           \
+    DOWNLOAD_BASE_URL="https://github.com/daggerok/${PRODUCT}/releases/download"    \
     JBOSS_EAP_PATCH='7.2.0'
-ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}"                                                         \
-    ARCHIVES_BASE_URL="${DOWNLOAD_BASE_URL}/archives"                                                  \
+ENV JBOSS_HOME="${JBOSS_USER_HOME}/${PRODUCT}"                                      \
+    ARCHIVES_BASE_URL="${DOWNLOAD_BASE_URL}/archives"                               \
     PATCHES_BASE_URL="${DOWNLOAD_BASE_URL}/${JBOSS_EAP_PATCH}"
 ENV PATH="${JBOSS_HOME}/bin:/tmp:${PATH}"
 USER root
-RUN ( apk fix     --no-cache || echo 'cannot fix.'         )                                        && \
-    ( apk upgrade --no-cache || echo 'cannot upgrade.'     )                                        && \
-    ( apk cache   -v   clean || echo 'cannot clean cache.' )                                        && \
-      apk add     --no-cache --update --upgrade                                                        \
-                  busybox-suid bash wget ca-certificates unzip sudo openssh-client shadow           && \
-    echo "${JBOSS_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                    && \
-    sed -i 's/.*requiretty$/Defaults !requiretty/' /etc/sudoers                                     && \
-    adduser -h ${JBOSS_USER_HOME} -s /bin/bash -D ${JBOSS_USER} ${JBOSS_USER}                       && \
+RUN ( apk fix     --no-cache || echo 'cannot fix.'         )                                    && \
+    ( apk upgrade --no-cache || echo 'cannot upgrade.'     )                                    && \
+    ( apk cache   -v   clean || echo 'cannot clean cache.' )                                    && \
+      apk add     --no-cache --update --upgrade                                                    \
+            busybox-suid bash wget ca-certificates unzip sudo openssh-client shadow curl        && \
+    echo "${JBOSS_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                && \
+    sed -i 's/.*requiretty$/Defaults !requiretty/' /etc/sudoers                                 && \
+    addgroup --system -g 1001 -S ${JBOSS_USER}                                                  && \
+    adduser --system -h ${JBOSS_USER_HOME} -s /bin/ash -D -u 1001 ${JBOSS_USER} ${JBOSS_USER}   && \
     usermod -a -G ${JBOSS_USER} ${JBOSS_USER}
 USER ${JBOSS_USER}
-CMD /bin/bash
-ENTRYPOINT standalone.sh
 EXPOSE 8080 8443 9990
+ENTRYPOINT ["/bin/ash", "-c"]
+CMD ["${JBOSS_HOME}/bin/standalone.s -b 0.0.0.0"]
 WORKDIR /tmp
 ADD --chown=jboss ./install.sh .
-RUN wget ${ARCHIVES_BASE_URL}/jce_policy-8.zip                                                         \
-         -q --no-cookies --no-check-certificate -O /tmp/jce_policy-8.zip                            && \
-    unzip -q /tmp/jce_policy-8.zip -d /tmp                                                          && \
-    ( sudo mv -f ${JAVA_HOME}/lib/security ${JAVA_HOME}/lib/backup-security || echo 'no backups.' ) && \
-    ( sudo mv -f /tmp/UnlimitedJCEPolicyJDK8 ${JAVA_HOME}/lib/security      || echo 'oops...'     ) && \
-    wget ${ARCHIVES_BASE_URL}/jboss-eap-7.2.0.zip                                                      \
-         -q --no-cookies --no-check-certificate -O /tmp/jboss-eap-7.2.0.zip                         && \
-    unzip -q /tmp/jboss-eap-7.2.0.zip -d ${JBOSS_USER_HOME}                                         && \
-    add-user.sh ${ADMIN_USER} ${ADMIN_PASSWORD} --silent                                            && \
+RUN wget ${ARCHIVES_BASE_URL}/jboss-eap-7.2.0.zip                                                                          \
+         -q --no-cookies --no-check-certificate -O /tmp/jboss-eap-7.2.0.zip                                             && \
+    unzip -q /tmp/jboss-eap-7.2.0.zip -d ${JBOSS_USER_HOME}                                                             && \
+    add-user.sh ${ADMIN_USER} ${ADMIN_PASSWORD} --silent                                                                && \
     echo 'JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0" \
-         ' >> ${JBOSS_HOME}/bin/standalone.conf                                                     && \
-    ( standalone.sh --admin-only                                                                       \
-      & ( sudo chmod +x /tmp/install.sh                                                             && \
-          install.sh                                                                                && \
-          sudo apk del --no-cache --no-network --purge busybox-suid unzip openssh-client shadow     && \
+         ' >> ${JBOSS_HOME}/bin/standalone.conf                                                                         && \
+    ( standalone.sh --admin-only                                                                                           \
+      & ( sudo chmod +x /tmp/install.sh                                                                                 && \
+          install.sh                                                                                                    && \
+          sudo apk del --no-cache --no-network --purge busybox-suid unzip openssh-client shadow                         && \
           ( sudo rm -rf /tmp/* /var/cache/apk /var/lib/apk /etc/apk/cache || echo 'cleanup!' ) ) )
 WORKDIR ${JBOSS_USER_HOME}
